% Project: MRI-Compatible Parallel Robot
% Description: Initialization Script of Robot Geometry
% Mishek Musa - Graduate Student Mechanical Engineering
% Medical Robotics Lab University of Arkansas
% created: January 2021
% last edited: January 2021

%% Initialize Robot Properties
alpha_B = 15.8;
alpha_P = 19.43;
r_B = 140.5;
r_P = 76.2;
initial_height = 170.2137;

%% Define Robot Geometry
alpha_B = alpha_B*pi/180;
alpha_P = alpha_P*pi/180;

theta_B = [alpha_B,... 
          alpha_B,...
          pi/3+alpha_B,... 
          pi/3-alpha_B,... 
          pi/3-alpha_B,... 
          pi/3+alpha_B];
      
theta_P = [pi/3-alpha_P,... 
          pi/3-alpha_P,...
          pi/3+alpha_P,... 
          alpha_P,... 
          alpha_P,... 
          pi/3+alpha_P];
      
Base_Pts = r_B* [ [cos(theta_B(1)), -sin(theta_B(1)), 0]',...
                     [cos(theta_B(2)), sin(theta_B(2)), 0]',...
                     [-cos(theta_B(3)), sin(theta_B(3)), 0]',...
                     [-cos(theta_B(4)), sin(theta_B(4)), 0]',...
                     [-cos(theta_B(5)), -sin(theta_B(5)), 0]',...
                     [-cos(theta_B(6)), -sin(theta_B(6)), 0]'];
                 
Plat_Pts = r_P*[ [cos(theta_P(1)), -sin(theta_P(1)), 0]',...
                      [cos(theta_P(2)), sin(theta_P(2)), 0]',...
                      [cos(theta_P(3)), sin(theta_P(3)), 0]',...
                      [-cos(theta_P(4)), sin(theta_P(4)), 0]',...
                      [-cos(theta_P(5)), -sin(theta_P(5)), 0]',...
                      [cos(theta_P(6)), -sin(theta_P(6)), 0]'];
